# Generated by Django 3.0.6 on 2020-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meme',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
