# Generated by Django 3.0.6 on 2020-05-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0002_auto_20200520_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
