# Generated by Django 3.0.6 on 2020-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0003_auto_20200520_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='tag1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meme',
            name='tag2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meme',
            name='tag3',
            field=models.TextField(null=True),
        ),
    ]
