# Generated by Django 3.0.6 on 2020-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0004_auto_20200520_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='tag1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='tag2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='tag3',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
