# Generated by Django 3.0.6 on 2020-06-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0005_auto_20200520_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='downvoted_by',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AddField(
            model_name='meme',
            name='upvoted_by',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
