# Generated by Django 3.0.6 on 2020-06-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0006_auto_20200610_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='meme',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='meme',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
