# Generated by Django 3.0.6 on 2020-06-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0007_auto_20200610_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='downvoted_by',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='upvoted_by',
            field=models.TextField(null=True),
        ),
    ]
