# Generated by Django 3.0.6 on 2020-06-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0009_auto_20200613_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memopolis.Comment'),
        ),
    ]
