# Generated by Django 3.0.6 on 2020-06-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0010_meme_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
