# Generated by Django 3.0.6 on 2020-06-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0012_auto_20200615_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memopolis.Meme'),
        ),
    ]
