# Generated by Django 3.0.6 on 2020-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0014_auto_20200615_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downvoted_by',
            field=models.TextField(default='n, n,'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvoted_by',
            field=models.TextField(default='n, n,'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='downvoted_by',
            field=models.TextField(default='n, n,'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='upvoted_by',
            field=models.TextField(default='n, n,'),
        ),
    ]
