# Generated by Django 3.0.6 on 2020-06-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0016_auto_20200617_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvoted_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='upvoted_by',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='upvotes',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('belongs_to', models.ManyToManyField(null=True, to='memopolis.Meme')),
            ],
        ),
    ]
