# Generated by Django 3.0.6 on 2020-06-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0019_auto_20200629_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='meme',
            name='tags',
            field=models.ManyToManyField(to='memopolis.Tag'),
        ),
    ]
