# Generated by Django 3.0.6 on 2020-07-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memopolis', '0021_auto_20200704_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
