# Generated by Django 3.0.7 on 2021-01-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200605_2248'),
        ('memopolis', '0024_badge_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='parent',
        ),
        migrations.AddField(
            model_name='badge',
            name='parent',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
